language: ruby
before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get -y install libtag1-dev
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
gemfile:
  - gemfiles/Gemfile.activesupport-3.x
  - gemfiles/Gemfile.activesupport-4.x
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.activesupport-4.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.activesupport-3.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activesupport-3.x